vi/Models/movie.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace vi.Models
{
    public class movie
    {
        public int  id { get; set;}
        [Required]
        [StringLength(255)]
        [Display(Name = "Movie Name")]
        public string name{ set; get; }
        
        public Genre genreType { get; set; }
        [Required]
        [Display(Name ="Genre Type")]
        public byte genreTypeId { get; set; }
        public DateTime dateAdded { get; set; }
        [Display(Name ="Release Date")]
        public DateTime dateReleased { get; set; }
        [Display(Name = "Number of Stock")]
        [Range(1,20)]
        [Required]
        public int stockAvailable { get; set; }
            

    }
}

vi/Controllers/movieController.cs
using Microsoft.Ajax.Utilities;
using System;
using System.Data.Entity;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using vi.Models;
using vi.viewModel;

namespace vi.Controllers
{
    public class movieController : Controller
    {
        public ApplicationDbContext _context;
        public movieController()
        {
            _context = new ApplicationDbContext();
        }
        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }
        // GET: movie
        public ActionResult random()
        {
            var movie = new movie() { name = "shrek" };
            var customer = new List<customer>
            {
                new customer{name="cust1"},
                new customer{name="cust2"}
            };
            var viewmodel = new RandomMovieViewModel
            {
                movie = movie,
                customers = customer,
            };
            return View(viewmodel);
        }
        [Route("movies/{year:regex(\\d{4})}/{month:regex(\\d{2}):range(1,12)}")]
        public ActionResult byreleased(int year, int month)
        {
            return Content(year + "/" + month);
        }
        [Route("movies")]
        public ActionResult movies()
        {
            var movie = _context.movies.Include(m => m.genreType).ToList();

            return View(movie);
        }
        [Route("movies/new")]
        public ActionResult New(){
            var movie = new AddMoviesViewModel
            {                
                Genres=_context.Genres.ToList(),
            };
            return View(movie);
        }
        [HttpPost]
        public ActionResult AddMovie(movie movie)
        {
            if (!ModelState.IsValid)
            {
                var Errmovie = new AddMoviesViewModel
                {
                    Movie= movie,
                    Genres = _context.Genres.ToList(),
                };
                return View("New",Errmovie);
                
            }
            if (movie.id == 0)
            {
                movie.dateAdded = DateTime.Now;
                _context.movies.Add(movie);
            }
            else
            {
                var MovieInDb = _context.movies.Single(m => m.id == movie.id);
                MovieInDb.dateReleased = movie.dateReleased;
                MovieInDb.name = movie.name;
                MovieInDb.genreTypeId = movie.genreTypeId;
                MovieInDb.stockAvailable = movie.stockAvailable;
            }
            _context.SaveChanges();
            return RedirectToAction("movies");
        }
        public ActionResult Edit(int id)
        {
            var movie = new AddMoviesViewModel
            {
                Movie = _context.movies.Single(m => m.id == id),
                Genres = _context.Genres.ToList(),
            };
            return View("New", movie);
        }
    }
}

vi/Views/movie/New.cshtml
@model vi.viewModel.AddMoviesViewModel
@{

    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>
    @if (Model.Movie == null)
    {
        <text>New</text>
        ViewBag.Title = "New";

    }
    else
    {
        <text>Edit
        </text>
        ViewBag.Title = "Edit";
    } Movie
</h2>

@using (@Html.BeginForm("AddMovie", "movie"))
{@Html.ValidationSummary(true,"Fill all the details")
<div class="form-group">
    @Html.LabelFor(m => m.Movie.name)
    @Html.TextBoxFor(m => m.Movie.name, new { @class = "form-control" })
    @Html.ValidationMessageFor(m=>m.Movie.name)
</div>
<div class="form-group">
    @Html.LabelFor(m => m.Movie.dateReleased)
    @Html.TextBoxFor(m => m.Movie.dateReleased, "{0:d MMM yyyy}", new { @class = "form-control" })
    @Html.ValidationMessageFor(m => m.Movie.dateReleased)
</div>
<div class="form-group">
    @Html.LabelFor(m => m.Movie.genreTypeId)
    @Html.DropDownListFor(m => m.Movie.genreTypeId, new SelectList(Model.Genres, "Id", "genre"), " ", new { @class = "form-control" })
    @Html.ValidationMessageFor(m => m.Movie.genreTypeId)
</div>
<div class="form-group">
    @Html.LabelFor(m => m.Movie.stockAvailable)
    @Html.TextBoxFor(m => m.Movie.stockAvailable, new { @class = "form-control" })
    @Html.ValidationMessageFor(m => m.Movie.stockAvailable)
</div>
<div class="form-group">
    @Html.HiddenFor(m => m.Movie.id)
    @Html.AntiForgeryToken()
    <button type="submit" class="btn btn-primary">Add</button>
</div>
}
@section scripts{
    @Scripts.Render("~/bundles/jqueryval");
}

vi/Views/movie/movies.cshtml
@using vi.viewModel

@{
    ViewBag.Title = "Movies";
    
}
<h1> Movies</h1>
@Html.ActionLink("New","new","movie",null,new { @class="btn btn-primary"})
   
   

    <table class="table-bordered table table-responsive table-hover">
        <thead ><tr class="success">
            <th>Movie</th>
            <th>Genre</th>
            </tr></thead>
            @foreach(var i in Model)
            {
    <tr>
        <td>
           @Html.ActionLink((string)i.name, "Edit", "movie",new { id=i.id},null)
        </td>
        <td>
            @i.genreType.genre
        </td>

    </tr>
            }
    
    </table>

vi/Views/movie/random.cshtml
@model vi.viewModel.RandomMovieViewModel
@{
    ViewBag.Title = "random";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Model.movie.name</h2>

<ul>
    @if (Model.movie.name.Equals("shrek"))
    {
        foreach(var i in Model.customers)
        {
            <li>
                @i.id
                </li>
        }
    }
    </ul>